app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

ekino_wordpress:
    resource: "@EkinoWordpressBundle/Resources/config/routing.xml"

sbs_adminlte:
    resource: "@SbSAdminLTEBundle/Resources/config/routing.xml"
