app:
    resource: '@AppBundle/Controller/'
    type: annotation

ekino_wordpress:
    resource: "@EkinoWordpressBundle/Resources/config/routing.xml"

sbs_adminlte:
    resource: "@SbSAdminLTEBundle/Resources/config/routing.xml"
